selenide.baseUrl=http://localhost:3000
selenide.browser=edge
selenide.browserSize=1600x1080
selenide.headless=true
selenide.timeout=10000
selenide.downloadsFolder=target/build/downloads
selenide.reportsFolder=target/build/reports
# Save Browser logs to file instead of standard output
selenide.webdriverLogsEnabled=true